import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {rm} from 'node:fs/promises';
import request from 'supertest';
process.env.NODE_ENV='test';process.env.SESSION_SECRET=randomBytes(48).toString('hex');process.env.OWNER_SETUP_KEY=randomBytes(32).toString('hex');process.env.TURSO_DATABASE_URL='file:data/test-'+Date.now()+'.db';delete process.env.CLOUDINARY_CLOUD_NAME;
const {app}=await import('../src/server.js');const {rows,one,db}=await import('../src/db.js');
const {identifierValid}=await import('../src/verification.js');
const image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII=','base64');
const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
const base=`http://127.0.0.1:${server.address().port}`;
const owner=request.agent(base),seller=request.agent(base),buyer=request.agent(base),other=request.agent(base),anon=request.agent(base);
async function token(agent,path='/login'){const r=await agent.get(path);assert.equal(r.status,200,r.text.slice(0,200));const m=r.text.match(/name="_csrf" value="([a-f0-9]+)"/);assert.ok(m,`Missing CSRF at ${path}`);return m[1];}
const credentials={password:'VeryStrongTestPassword123!'};
async function register(agent,role,email){const csrf=await token(agent,'/register');return agent.post('/register').type('form').send({_csrf:csrf,name:role+' Student',email,role,university:'American University of Beirut',location:'Beirut',phone:'+96171123456',...credentials});}
async function post(agent,url,body={},path='/account'){const csrf=await token(agent,path);return agent.post(url).type('form').send({_csrf:csrf,...body});}
let id,secondId,sellerId;
test('buyer, seller, owner and security workflows',async()=>{
 assert.equal((await anon.get('/')).status,200);
 assert.equal((await anon.get('/health')).body.status,'ok');
 assert.equal((await register(seller,'seller','seller@example.com')).status,302);
 assert.equal((await register(other,'seller','other@example.com')).status,302);
 assert.equal((await register(buyer,'buyer','buyer@example.com')).status,302);
 assert.equal((await register(anon,'admin','attacker@example.com')).status,400);
 assert.equal((await buyer.get('/control')).status,404);
 assert.equal((await seller.get('/control/listings')).status,404);
 assert.equal((await buyer.get('/sell')).status,403);
 assert.equal((await seller.post('/sell').field('_csrf','wrong')).status,403);
 assert.equal((await anon.post('/sell')).status,403);
 const setup=await token(owner,'/owner/setup');
 assert.equal((await owner.post('/owner/setup').type('form').send({_csrf:setup,setup_key:'wrong',name:'Owner',email:'owner@example.com',...credentials})).status,403);
 assert.equal((await owner.post('/owner/setup').type('form').send({_csrf:setup,setup_key:process.env.OWNER_SETUP_KEY,name:'Owner',email:'owner@example.com',...credentials})).status,302);
 assert.equal((await owner.get('/owner/setup')).status,404);
 assert.equal((await owner.get('/control')).status,200);
 for(const section of ['listings','verification','users','categories','analytics','settings','reports'])assert.equal((await owner.get('/control/'+section)).status,200);
 await post(owner,'/logout',{},'/control');
 assert.equal((await post(owner,'/login',{email:'owner@example.com',...credentials},'/login')).status,401);
 assert.equal((await post(owner,'/owner/login',{email:'owner@example.com',...credentials},'/owner/login')).status,302);
 const data={title:'Apple MacBook Air M1 2020 8GB 256GB',category_id:'2',brand:'Apple',model:'M1 2020',author:'',condition:'Good',price:'450',university:'AUB',location:'Beirut',description:'Excellent working laptop with charger included and a few minor marks.'};
 const create=async(agent,d)=>{const csrf=await token(agent,'/sell');let r=agent.post('/sell').field('_csrf',csrf);for(const [k,v] of Object.entries(d))r=r.field(k,v);return r.attach('photos',image,{filename:'photo.png',contentType:'image/png'});};
 assert.equal((await create(seller,data)).status,302);
 id=(await one('SELECT id,seller_id FROM products')).id;sellerId=(await one('SELECT seller_id FROM products WHERE id=?',[id])).seller_id;
 assert.equal((await one('SELECT status FROM products WHERE id=?',[id])).status,'PENDING');
 assert.equal((await anon.get('/products/'+id)).status,404);
 assert.equal((await other.get('/listings/'+id+'/edit')).status,404);
 assert.equal((await post(other,'/listings/'+id+'/sold')).status,404);
 assert.equal((await buyer.post('/listings/'+id+'/edit').field('_csrf',await token(buyer,'/account'))).status,403);
 assert.equal((await post(owner,'/control/listings/'+id,{action:'approve'},'/control')).status,302);
 let detail=await buyer.get('/products/'+id);assert.equal(detail.status,200);
 assert.equal((await post(buyer,'/products/'+id+'/favorite')).status,302);
 assert.equal((await rows('SELECT * FROM favorites')).length,1);
 assert.equal((await post(buyer,'/products/'+id+'/favorite',{remove:'1'})).status,302);
 assert.equal((await rows('SELECT * FROM favorites')).length,0);
 assert.equal((await buyer.get('/marketplace?q=MacBook&min=400&max=500&sort=low')).status,200);
 assert.equal((await post(buyer,'/products/'+id+'/contact',{channel:'whatsapp'})).status,200);
 assert.equal((await post(buyer,'/products/'+id+'/contact',{channel:'email'})).status,200);
 assert.equal((await one('SELECT contacts FROM products WHERE id=?',[id])).contacts,2);
 let verification=await seller.post('/listings/'+id+'/verification').field('_csrf',await token(seller,'/listings/'+id+'/verification')).field('kind','Serial').field('identifier','PRIVATE-SERIAL-1234').attach('evidence',image,{filename:'proof.png',contentType:'image/png'});assert.equal(verification.status,302);
 const evidence=(await one('SELECT id FROM verification_evidence')).id;
 assert.equal((await buyer.get('/evidence/'+evidence)).status,404);
 assert.equal((await other.get('/evidence/'+evidence)).status,404);
 assert.equal((await seller.get('/evidence/'+evidence)).status,200);
 assert.equal((await owner.get('/evidence/'+evidence)).status,200);
 assert.equal((await anon.get('/evidence/'+evidence)).status,302);
 assert.equal((await post(owner,'/control/verification/'+id,{status:'Verified',notes:'Proof reviewed'},'/control')).status,302);
 detail=await buyer.get('/products/'+id);assert.match(detail.text,/CampusLoop Verified/);assert.ok(!detail.text.includes('PRIVATE-SERIAL-1234'));assert.ok(!detail.text.includes('/evidence/'));
 assert.equal((await post(owner,'/control/listings/'+id,{action:'feature'},'/control')).status,302);
 assert.match((await anon.get('/')).text,/Featured/);
 let edit=seller.post('/listings/'+id+'/edit').field('_csrf',await token(seller,'/listings/'+id+'/edit'));for(const [k,v] of Object.entries({...data,price:'420'}))edit=edit.field(k,v);assert.equal((await edit.attach('photos',image,{filename:'extra.png',contentType:'image/png'})).status,302);
 assert.equal((await one('SELECT COUNT(*) n FROM product_images WHERE product_id=?',[id])).n,2);
 assert.equal((await one('SELECT status FROM products WHERE id=?',[id])).status,'PENDING');
 assert.equal((await one('SELECT status FROM product_verifications WHERE product_id=?',[id])).status,'Under review');
 assert.equal((await owner.get('/listings/'+id+'/edit')).status,200);
 let ownerEdit=owner.post('/listings/'+id+'/edit').field('_csrf',await token(owner,'/listings/'+id+'/edit'));for(const [k,v] of Object.entries({...data,title:'Apple MacBook Air M1 2020 — reviewed'}))ownerEdit=ownerEdit.field(k,v);assert.equal((await ownerEdit).status,302);
 await post(owner,'/control/listings/'+id,{action:'approve'},'/control');
 assert.equal((await post(buyer,'/products/'+id+'/report',{reason:'Please check the provided model details.'})).status,200);
 assert.equal((await owner.get('/control/reports')).status,200);
 const report=(await one('SELECT id FROM reports')).id;assert.equal((await post(owner,'/control/reports/'+report,{},'/control')).status,302);
 assert.equal((await post(owner,'/control/users/'+sellerId,{action:'suspend'},'/control')).status,302);
 assert.equal((await seller.get('/account')).status,302);
 assert.equal((await buyer.get('/products/'+id)).status,404);
 assert.equal((await post(owner,'/control/users/'+sellerId,{action:'restore'},'/control')).status,302);
 assert.equal((await post(seller,'/login',{email:'seller@example.com',...credentials},'/login')).status,302);
 await post(owner,'/control/listings/'+id,{action:'activate'},'/control');
 assert.equal((await create(seller,{...data,title:'Casio FX-991ES Plus scientific calculator',category_id:'4',brand:'Casio',model:'FX-991ES'})).status,302);
 secondId=(await rows('SELECT id FROM products WHERE id<>?',[id]))[0].id;
 assert.equal((await post(seller,'/listings/'+secondId+'/sold')).status,302);
 assert.equal((await one('SELECT status FROM products WHERE id=?',[secondId])).status,'SOLD');
 assert.equal((await seller.get('/account')).status,200);
 let invalidRequest=seller.post('/sell').field('_csrf',await token(seller,'/sell'));for(const [k,v] of Object.entries(data))invalidRequest=invalidRequest.field(k,v);
 const invalidFile=await invalidRequest.attach('photos',Buffer.from('not an image'),{filename:'bad.png',contentType:'image/png'});assert.equal(invalidFile.status,400);assert.match(invalidFile.text,/Upload JPG, PNG or WEBP/);
 const large=await seller.post('/sell').field('_csrf',await token(seller,'/sell')).attach('photos',Buffer.alloc(5*1024*1024+1),{filename:'large.png',contentType:'image/png'});assert.equal(large.status,400);
 const settings=Object.fromEntries((await rows('SELECT * FROM site_settings')).map(s=>[s.key,s.value]));settings.headline='A new chapter for campus essentials.';
 assert.equal((await post(owner,'/control/settings',settings,'/control')).status,302);assert.match((await anon.get('/')).text,/A new chapter for campus essentials/);
 assert.equal((await post(owner,'/control/categories',{name:'Sports essentials',position:'11'},'/control')).status,302);
 assert.match((await anon.get('/')).text,/Sports essentials/);
 assert.equal((await post(buyer,'/account',{name:'Buyer Updated',university:'LAU',location:'Byblos',phone:''})).status,302);
 await post(buyer,'/logout');assert.equal((await buyer.get('/account')).status,302);
 assert.equal((await post(buyer,'/login',{email:'buyer@example.com',...credentials},'/login')).status,302);
 assert.equal((await post(seller,'/listings/'+secondId+'/delete')).status,302);
 assert.equal((await one('SELECT * FROM products WHERE id=?',[secondId])),undefined);
 assert.equal((await buyer.post('/account').type('form').send({_csrf:'invalid',name:'Attack'})).status,403);
});
test('IMEI and ISBN checks validate checksums, not authenticity',()=>{assert.equal(identifierValid('IMEI','490154203237518'),true);assert.equal(identifierValid('IMEI','490154203237519'),false);assert.equal(identifierValid('ISBN','9780306406157'),true);assert.equal(identifierValid('ISBN','0306406152'),true);assert.equal(identifierValid('ISBN','9780306406158'),false);});
after(async()=>{await new Promise(resolve=>server.close(resolve));db.close();try{await rm(process.env.TURSO_DATABASE_URL.slice(5),{force:true});}catch(e){if(e.code!=='EBUSY')throw e;}});
